---
title: "Functional Similarity"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Functional Similarity}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#library(fsmc)
```

## Examples

### Misosoup 
```{r}
# Initialise list
msR <- list()

# Read all solutions and save to list
for (f in list.files("../inst/extdata/test_2", full.names = TRUE)) {
  tb <- read.csv(file = f) %>%
    tibble::as_tibble() %>%
    dplyr::rename(
      MO = "nodeB",
      met = "nodeA",
      val = "weight"
    ) %>%
    dplyr::select(dplyr::all_of(c("MO", "met", "val")))

  # Extract solution name
  name <- stringr::str_split(f, "/")[[1]][5] %>% stringr::str_remove(".csv")

  # Assign solution to list
  msR[[name]] <- tb
}
```


```{r}
msR_alignments <- list()
done <- c()
for (c1 in names(msR)) {
  for (c2 in names(msR)) {
    if (c1 == c2 | c2 %in% done) next
    alignment_name <- paste0(c1, "-", c2)
    alignment_list <- list()
    alignment_list[[c1]] <- msR[[c1]]
    alignment_list[[c2]] <- msR[[c2]]
    msR_alignments[[alignment_name]] <- MiCo.align.v2(alignment_list)
  }
  done <- c(done, c1)
  cat("Alignment:", round(length(done)/length(msR)*100, 2), "%     \r")
}
```

## Analyse the alignments

### Binary Matrices
What is the minimum number of edges and what is the maximum number of edges?
What is the number of aligned edges?

### Jaccard Score
`sum(mat, na.rm = TRUE) / (ncol(mat) * nrow(mat) - (is.na(mat) %>% sum()))`
If this value is != 1 for any alignments, these alignments have partial differences that would be interesting to investigate. 

```{r}
msR_tb <- tibble::tibble(
  alignment_js = numeric(length = 1540),
  min_n_reacts = numeric(length = 1540),
  max_n_reacts = numeric(length = 1540),
  aligned_reacts = numeric(length = 1540),
)
```

```{r}
for (a in seq(length(msR_alignments))) {
  
  c1 <- msR_alignments[[a]]$bin_matrices[[1]]
  c2 <- msR_alignments[[a]]$bin_matrices[[2]]
  alignment <- msR_alignments[[a]]$alignment

  c1_sum <- sum(c1[!is.na(c1)] != 0)
  c2_sum <- sum(c2[!is.na(c2)] != 0)
  al_sum <- sum(alignment[!is.na(alignment)] != 0)
  
  msR_tb$alignment_js[a] <- al_sum / min(c1_sum, c2_sum)
  msR_tb$min_n_reacts[a] <- min(c1_sum, c2_sum)
  msR_tb$max_n_reacts[a] <- max(c1_sum, c2_sum)
  msR_tb$aligned_reacts[a] <- al_sum
}
```

